# Generated by Django 4.2.1 on 2023-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Мужской"), (2, "Женский")], default=1
            ),
        ),
    ]
