# Generated by Django 4.2.1 on 2023-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_sex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
