# Generated by Django 4.2.1 on 2023-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coins",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество коинов"
            ),
        ),
    ]
