version: '3.9'


services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: hackathon-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  server:
    build:
      context: .
      dockerfile: web.Dockerfile
      target: production
    depends_on:
      - db
    restart: always
    container_name: hackathon-server
    volumes:
      - ./static:/app/src/static
      - ./media:/app/src/media
    env_file: .env
    ports:
      - ${SERVER_PORT-8080}:8000

volumes:
  postgres_data:
