version: '3.9'


services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: hackathon-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  redis:
    image: redis
    container_name: mtusi-redis
    restart: always
    ports:
      - ${REDIS_PORT-6397}:6397

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-base
    restart: always
    container_name: server
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    env_file: .env
    ports:
      - ${SERVER_PORT-8000}:8000
    entrypoint: ["/code/entrypoint.sh"]
    depends_on:
      - db
      - redis

  worker:
    container_name: celery-worker
    build: .
    command: celery -A src.hackathon worker -l info
    env_file:
      .env
    depends_on:
      - redis
      - server

volumes:
  postgres_data:
