# Generated by Django 4.2.1 on 2023-05-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["number_course"],
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
    ]
