# Generated by Django 4.2.1 on 2023-05-15 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Место проведения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Является активным"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="events_participating", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
