# Generated by Django 4.2.1 on 2023-05-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("events", "0003_alter_event_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.image"
            ),
        ),
    ]
